game = {
    "money": 100,
    "day": 1,
    "capacity": 3,
    "dogs_processed_today": 0,
    "total_dogs": 0
}

dogs = []

dog_directory = [
    ("Bailey", "Labrador Retriever", 65, 4, "high"),
    ("Clover", "Beagle", 24, 6, "calm"),
    ("Pesto", "Beagle", 23, 2, "high"),
    ("Duke", "German Shepherd", 78, 3, "high"),
    ("Poppy", "Cavalier King Charles Spaniel", 16, 8, "calm"),
    ("Milo", "Border Collie", 42, 2, "high"),
    ("Rosie", "Basset Hound", 48, 7, "calm"),
    ("Rocky", "Boxer", 68, 5, "high"),
    ("Luna", "Miniature Poodle", 19, 3, "calm"),
    ("Scout", "Australian Shepherd", 52, 4, "high"),
    ("Daisy", "French Bulldog", 26, 6, "calm"),
    ("Tucker", "Siberian Husky", 58, 2, "high"),
    ("Maggie", "Shih Tzu", 13, 9, "calm"),
    ("Finn", "Golden Retriever", 62, 3, "high"),
    ("Olive", "Pembroke Welsh Corgi", 27, 5, "calm"),
    ("Ranger", "Rottweiler", 104, 4, "high"),
    ("Winnie", "Pug", 18, 7, "calm"),
    ("Jasper", "Australian Cattle Dog", 47, 2, "high"),
    ("Hazel", "English Springer Spaniel", 44, 6, "high"),
    ("Otis", "Boston Terrier", 22, 8, "calm"),
    ("Maple", "Miniature Schnauzer", 17, 4, "high"),
    ("Archie", "Yorkshire Terrier", 8, 3, "high"),
    ("Nala", "Doberman Pinscher", 76, 5, "high"),
    ("Benny", "Dachshund", 22, 9, "calm"),
    ("Ivy", "Whippet", 28, 4, "high"),
    ("Murphy", "Chihuahua", 6, 6, "high"),
    ("Ruby", "Cocker Spaniel", 27, 5, "high"),
    ("Bruno", "Great Dane", 145, 3, "calm"),
    ("Pearl", "Maltese", 7, 10, "calm"),
    ("Ziggy", "Pomeranian", 9, 2, "high"),
    ("Millie", "Bernese Mountain Dog", 88, 6, "calm"),
    ("Cooper", "Labrador Retriever", 72, 7, "high"),
    ("Fern", "Beagle", 28, 4, "high"),
    ("Samson", "German Shepherd", 84, 8, "calm"),
    ("Maisie", "Cavalier King Charles Spaniel", 14, 3, "high"),
    ("Riley", "Border Collie", 36, 5, "high"),
    ("Mabel", "Basset Hound", 54, 10, "calm"),
    ("Baxter", "Boxer", 74, 3, "high"),
    ("Tilly", "Standard Poodle", 48, 7, "calm"),
    ("Ace", "Australian Shepherd", 58, 6, "high"),
    ("Nellie", "French Bulldog", 21, 4, "calm"),
    ("Koda", "Siberian Husky", 48, 5, "high"),
    ("Phoebe", "Shih Tzu", 11, 4, "calm"),
    ("Harvey", "Golden Retriever", 74, 8, "calm"),
    ("Titan", "Rottweiler", 118, 7, "calm"),
    ("Gus", "Pug", 20, 5, "calm"),
    ("Indy", "Australian Cattle Dog", 42, 4, "high"),
    ("Lottie", "English Springer Spaniel", 49, 3, "high"),
    ("Percy", "Boston Terrier", 18, 6, "calm"),
    ("Suki", "Miniature Schnauzer", 15, 8, "calm"),
    ("Remy", "Yorkshire Terrier", 6, 7, "high"),
    ("Freya", "Doberman Pinscher", 68, 3, "high"),
    ("Louie", "Dachshund", 17, 2, "high"),
    ("Skye", "Whippet", 33, 7, "high"),
    ("Chico", "Chihuahua", 5, 11, "calm"),
    ("Mochi", "Cocker Spaniel", 24, 2, "high"),
    ("Atlas", "Great Dane", 158, 6, "calm"),
    ("Elsie", "Maltese", 9, 5, "calm"),
    ("Pip", "Pomeranian", 7, 6, "high"),
    ("Moose", "Bernese Mountain Dog", 102, 4, "calm"),
    ("Roscoe", "Labrador Retriever", 58, 10, "calm"),
    ("Edie", "Beagle", 21, 11, "calm"),
    ("Kaiser", "German Shepherd", 72, 6, "high"),
    ("Annie", "Cavalier King Charles Spaniel", 18, 6, "calm"),
    ("Dash", "Border Collie", 48, 3, "high"),
    ("Walter", "Basset Hound", 43, 5, "calm"),
    ("Cleo", "Boxer", 59, 9, "calm"),
    ("Sunny", "Miniature Poodle", 14, 8, "high"),
    ("Banjo", "Australian Shepherd", 46, 9, "calm"),
    ("Minnie", "French Bulldog", 28, 3, "calm"),
    ("Yuki", "Siberian Husky", 55, 8, "high"),
    ("Theo", "Shih Tzu", 15, 6, "calm"),
    ("Honey", "Golden Retriever", 57, 2, "high"),
    ("Coco", "Pembroke Welsh Corgi", 30, 8, "calm"),
    ("Dottie", "Rottweiler", 96, 3, "high"),
    ("Frankie", "Pug", 16, 3, "high"),
    ("Penny", "Australian Cattle Dog", 50, 7, "high"),
    ("Ollie", "English Springer Spaniel", 38, 8, "calm"),
    ("Trixie", "Boston Terrier", 25, 4, "high"),
    ("Eddie", "Miniature Schnauzer", 19, 3, "high"),
    ("Gigi", "Yorkshire Terrier", 7, 10, "calm"),
    ("Boone", "Doberman Pinscher", 88, 8, "calm"),
    ("Waffles", "Dachshund", 25, 6, "calm"),
    ("Lacey", "Whippet", 25, 2, "high"),
    ("Nacho", "Chihuahua", 8, 4, "high"),
    ("Murray", "Cocker Spaniel", 30, 9, "calm"),
    ("Darla", "Great Dane", 132, 5, "calm"),
    ("Bubbles", "Maltese", 6, 3, "high"),
    ("Rufus", "Pomeranian", 11, 8, "calm"),
    ("Sasha", "Bernese Mountain Dog", 78, 2, "high"),
    ("Hank", "German Shepherd", 90, 10, "calm"),
    ("Nina", "Cavalier King Charles Spaniel", 13, 11, "calm"),
    ("Bowie", "Border Collie", 39, 8, "high"),
    ("Agnes", "Basset Hound", 61, 12, "calm"),
    ("Rocco", "Boxer", 80, 7, "high"),
    ("Fifi", "Standard Poodle", 56, 4, "high"),
    ("Quincy", "Australian Shepherd", 49, 3, "high"),
    ("Marnie", "French Bulldog", 18, 9, "calm"),
    ("Echo", "Siberian Husky", 40, 11, "calm"),
    ("Lulu", "Shih Tzu", 9, 2, "high"),
]

dog_directory = [
    {"name": name, "breed": breed, "weight": weight, "age": age, "energy": energy}
    for name, breed, weight, age, energy in dog_directory
]

available_dogs = list(dog_directory)
